### ISSUE TITLE
OS X Installer wrecks Homebrew installation

### ISSUE THREAD

**Issue by mhetrick** [monome/install#1]
Hello,

I ran the monome installer on OS X and it caused a lot of chaos with my Homebrew installation. It installs liblo and libmonome into the folders typically used by Homebrew and changes the permissions on some of the folders. It ended up temporarily breaking many Homebrew commands for me. To see some of the problems, run brew doctor after using this installer.

**Comment by wrl** [comment]
with the upcoming 1.4 release, we've instead packaged serialosc as a bundle that lives in `/Library/Application Support`, so we won't install stuff in `/usr/local` anymore. that said, the new installer will _remove_ the old files which were installed in `/usr/local`, so there may be some breakage there, unfortunately.
